{% set name = "spacy-lookups-data" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spacy_lookups_data-{{ version }}.tar.gz
  sha256: 4f58f3c9cbce50b75bdd57a1c84b5c9a1f17ffa23b285e724ee066fef64886be

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"
  entry_points:
    - hr = spacy_lookups_data:hr
    - pt = spacy_lookups_data:pt
    - sv = spacy_lookups_data:sv
    - da = spacy_lookups_data:da
    - ca = spacy_lookups_data:ca
    - es = spacy_lookups_data:es
    - fr = spacy_lookups_data:fr
    - nb = spacy_lookups_data:nb
    - tr = spacy_lookups_data:tr
    - de = spacy_lookups_data:de
    - it = spacy_lookups_data:it
    - lt = spacy_lookups_data:lt
    - nl = spacy_lookups_data:nl
    - ro = spacy_lookups_data:ro
    - sr = spacy_lookups_data:sr
    - id = spacy_lookups_data:id_
    - hu = spacy_lookups_data:hu
    - fa = spacy_lookups_data:fa
    - en = spacy_lookups_data:en
    - el = spacy_lookups_data:el
    - bn = spacy_lookups_data:bn
    - tl = spacy_lookups_data:tl
    - ur = spacy_lookups_data:ur


requirements:
  host:
    - python
    - pip
    - setuptools
    - srsly >=0.1.0,<1.1.0
  run:
    - python
    - setuptools

test:
  imports:
    - spacy_lookups_data

about:
  home: https://github.com/explosion/spacy-lookups-data
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: 'Additional lookup tables and data resources for spaCy'

  # The remaining entries in this section are optional, but recommended.
  description: |
    This package contains additional data files to be used with spaCy v2.2+.
    When it's installed in the same environment as spaCy, this package makes
    the resources for each language available as an entry point, which spaCy
    checks when setting up the Vocab and Lookups.
  doc_url: https://spacy.io/
  dev_url: https://github.com/explosion/spacy-lookups-data

extra:
  recipe-maintainers:
    - honnibal
    - ines
