{% set name = "spacy-lookups-data" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spacy_lookups_data-{{ version }}.tar.gz
  sha256: ab6865548fb866d479090e31108a7e25ed192a11fcb09896e7116328cdc52be1

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools
    - srsly >=0.1.0,<1.1.0
  run:
    - python >=3.6
    - setuptools

test:
  imports:
    - spacy_lookups_data

about:
  home: https://github.com/explosion/spacy-lookups-data
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: Additional lookup tables and data resources for spaCy

  # The remaining entries in this section are optional, but recommended.
  description: |
    This package contains additional data files to be used with spaCy v2.2+.
    When it's installed in the same environment as spaCy, this package makes
    the resources for each language available as an entry point, which spaCy
    checks when setting up the Vocab and Lookups.
  doc_url: https://spacy.io/
  dev_url: https://github.com/explosion/spacy-lookups-data

extra:
  recipe-maintainers:
    - adrianeboyd
    - honnibal
    - ines
